# -*- coding: utf-8 -*-
"""1901147_Ahmad_05_Lab3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1quQIRg4_ZLo03mzfX5vBRhQEd2KI7Xdb
"""

import re

regex = []
print("Number of regular expressions?")
no_of_regex = int(input())

i = 0
while(i < no_of_regex):
    temp = input()
    temp += '$'
    regex.append(temp)
    i += 1

print("Number of examples?")
no_of_ex = int(input())
ex = []

for i in range(no_of_ex):
    ex.append(input())

for i in range(len(regex)):
    regex[i] = re.compile(regex[i])

for i in range(len(ex)):
    none_matched = 0
    for j in range(len(regex)):
        if(regex[j].match(ex[i])):
            print(f"YES, {j + 1}")
            break
        else:
            none_matched += 1

    if(none_matched == no_of_regex):
        print(f"NO, 0")

